export const defaultSchema = [
  {
    attr: 1792,
    canTrigger: true,
    code: 'temp_current',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '{"trigger":"direct"}',
    iconname: 'icon-dp_temp',
    id: 1,
    mode: 'ro',
    name: '当前温度',
    property: {
      unit: '℃',
      min: -100,
      max: 600,
      scale: 1,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1792,
    canTrigger: true,
    code: 'humidity_value',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '{"trigger":"direct"}',
    iconname: 'icon-shidu',
    id: 2,
    mode: 'ro',
    name: '湿度数值',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 768,
    canTrigger: true,
    code: 'battery_percentage',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '{"trigger":"direct"}',
    iconname: 'icon-dp_battery',
    id: 4,
    mode: 'ro',
    name: '电池电量',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'tamper_alarm',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_warming',
    id: 5,
    mode: 'ro',
    name: '防拆报警',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1760,
    canTrigger: false,
    code: 'maxtemp_set',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-setting',
    id: 10,
    mode: 'rw',
    name: '温度上限设置',
    property: {
      unit: '℃',
      min: -100,
      max: 600,
      scale: 1,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1760,
    canTrigger: false,
    code: 'minitemp_set',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-wendu1',
    id: 11,
    mode: 'rw',
    name: '温度下限设置',
    property: {
      unit: '℃',
      min: -100,
      max: 600,
      scale: 1,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1760,
    canTrigger: false,
    code: 'maxhum_set',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-setting',
    id: 12,
    mode: 'rw',
    name: '湿度上限设置',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1760,
    canTrigger: false,
    code: 'minihum_set',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-setting',
    id: 13,
    mode: 'rw',
    name: '湿度下限设置',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1792,
    canTrigger: true,
    code: 'temp_alarm',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '{"trigger":"direct"}',
    iconname: 'icon-baojing',
    id: 14,
    mode: 'ro',
    name: '温度报警',
    property: {
      range: ['loweralarm', 'upperalarm', 'cancel'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1792,
    canTrigger: true,
    code: 'hum_alarm',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '{"trigger":"direct"}',
    iconname: 'icon-baojing',
    id: 15,
    mode: 'ro',
    name: '湿度报警',
    property: {
      range: ['loweralarm', 'upperalarm', 'cancel'],
      type: 'enum',
    },
    type: 'obj',
  },
] as const;
