import { GetSmartDeviceModelDpSchema } from '@ray-js/panel-sdk';
import { keyBy } from 'lodash-es';

export const defaultSchema = [
  {
    code: 'switch_led',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_power2',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Switch',
    property: {
      type: 'bool',
    },
    subType: 'bool',
    id: 20,
    editPermission: false,
  },
  {
    code: 'work_mode',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_mode',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Work Mode',
    property: {
      range: ['white', 'colour', 'scene', 'music'],
      type: 'enum',
    },
    subType: 'enum',
    id: 21,
    editPermission: false,
  },
  {
    code: 'bright_value',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-liangdu',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'White Light Brightness',
    property: {
      unit: '',
      min: 10,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    subType: 'value',
    id: 22,
    editPermission: false,
  },
  {
    code: 'temp_value',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-lengnuan',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Warm Cool Value',
    property: {
      unit: '',
      min: 0,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    subType: 'value',
    id: 23,
    editPermission: false,
  },
  {
    code: 'colour_data',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_mode',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Colour Light',
    property: {
      type: 'string',
      maxlen: 255,
    },
    subType: 'string',
    id: 24,
    editPermission: false,
  },
  {
    code: 'countdown',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_time2',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Countdown',
    property: {
      unit: 's',
      min: 0,
      max: 86400,
      scale: 0,
      step: 1,
      type: 'value',
    },
    subType: 'value',
    id: 26,
    editPermission: false,
  },
  {
    code: 'music_data',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-deng',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Music Light',
    property: {
      type: 'string',
      maxlen: 255,
    },
    subType: 'string',
    id: 27,
    editPermission: false,
  },
  {
    code: 'dreamlightmic_music_data',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_mode',
    type: 'raw',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Fantasy Colour Local Music Rhythm',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    subType: 'raw',
    id: 52,
    editPermission: false,
  },
  {
    code: 'rgbic_linerlight_scene',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_mode',
    type: 'raw',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Colourful Scene',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    subType: 'raw',
    id: 56,
    editPermission: false,
  },
  {
    code: 'led_number_set',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_light',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'LED Point Number Setting',
    property: {
      unit: '',
      min: 0,
      max: 99999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    subType: 'value',
    id: 58,
    editPermission: false,
  },
  {
    code: 'segment_num_set',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-dp_light',
    type: 'obj',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Segment Number Setting',
    property: {
      unit: '',
      min: 2,
      max: 20,
      scale: 0,
      step: 1,
      type: 'value',
    },
    subType: 'value',
    id: 63,
    editPermission: false,
  },
  {
    code: 'paint_colour_1',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-edit',
    type: 'raw',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'Paint Colour 1',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    subType: 'raw',
    id: 69,
    editPermission: false,
  },
  {
    code: 'diy_scene',
    defaultValue: '',
    canTrigger: true,
    iconname: 'icon-yanse',
    type: 'raw',
    executable: true,
    mode: 'rw',
    defaultRecommend: false,
    name: 'DIY Scene',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    subType: 'raw',
    id: 74,
    editPermission: false,
  },
] as const;

export const lampSchemaMap = keyBy(defaultSchema, 'code') as GetSmartDeviceModelDpSchema<
  typeof defaultSchema
>;
