export const defaultSchema = [
  {
    attr: 0,
    canTrigger: true,
    code: 'get_terminal_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_block',
    id: 1,
    mode: 'rw',
    name: '心跳及DP数据召读',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'inverter_status',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 26,
    mode: 'ro',
    name: '逆变器常规信息',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'inverter_instant',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_lightning',
    id: 27,
    mode: 'ro',
    name: '逆变器动态数据',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'device_info',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 28,
    mode: 'ro',
    name: '逆变器设备数据string格式',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'alarm_msg',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-baojing',
    id: 29,
    mode: 'ro',
    name: '告警信息',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'model_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_i',
    id: 30,
    mode: 'ro',
    name: '逆变器心跳上报数据',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'function_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-a_nav_function',
    id: 31,
    mode: 'rw',
    name: '逆变器设置',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'ksd_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-setting',
    id: 32,
    mode: 'rw',
    name: '科士达设置',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'ksd_alarm',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_warming',
    id: 33,
    mode: 'rw',
    name: '科士达告警',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'mgrn_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-setting',
    id: 34,
    mode: 'rw',
    name: '迈格瑞能设置',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'mgrn_alarm',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_warming',
    id: 35,
    mode: 'rw',
    name: '迈格瑞能告警',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'jl_alarm',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_warming',
    id: 36,
    mode: 'rw',
    name: '锦浪告警',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
] as const;
