export const defaultSchema = [
  {
    attr: 1056,
    canTrigger: false,
    code: 'switch',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 1,
    mode: 'rw',
    name: '电源开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1569,
    canTrigger: false,
    code: 'switch_go',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power',
    id: 2,
    mode: 'rw',
    name: '清扫开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1568,
    canTrigger: false,
    code: 'mode',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 3,
    mode: 'rw',
    name: '清扫模式',
    property: {
      range: [
        'standby',
        'random',
        'smart',
        'wall_follow',
        'mop',
        'spiral',
        'left_spiral',
        'right_spiral',
        'left_bow',
        'right_bow',
        'partial_bow',
        'chargego',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1120,
    canTrigger: false,
    code: 'direction_control',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_wind',
    id: 4,
    mode: 'rw',
    name: '清扫方向',
    property: {
      range: ['forward', 'backward', 'turn_left', 'turn_right', 'stop', 'exit'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1602,
    canTrigger: true,
    code: 'status',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_dust',
    id: 5,
    mode: 'ro',
    name: '设备状态',
    property: {
      range: [
        'standby',
        'smart_clean',
        'wall_clean',
        'spot_clean',
        'mop_clean',
        'goto_charge',
        'charging',
        'charge_done',
        'paused',
        'cleaning',
        'sleep',
        'random_clean',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1090,
    canTrigger: true,
    code: 'battery_percentage',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    id: 6,
    mode: 'ro',
    name: '剩余电量',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'edge_brush_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    id: 7,
    mode: 'ro',
    name: '边刷寿命',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'roll_brush_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    id: 8,
    mode: 'ro',
    name: '滚刷寿命',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'filter_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    id: 9,
    mode: 'ro',
    name: '滤网寿命',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'edge_brush_life_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 10,
    mode: 'rw',
    name: '边刷重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'roll_brush_life_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 11,
    mode: 'rw',
    name: '滚刷重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'filter_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 12,
    mode: 'rw',
    name: '滤芯重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1056,
    canTrigger: false,
    code: 'seek',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_magnifier',
    id: 13,
    mode: 'rw',
    name: '寻找机器',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1056,
    canTrigger: false,
    code: 'suction',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-Strong',
    id: 14,
    mode: 'rw',
    name: '吸力选择',
    property: {
      range: ['gentle', 'normal', 'strong'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'clean_record',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_book',
    id: 15,
    mode: 'ro',
    name: '清扫记录',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'clean_area',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-icon-test10',
    id: 16,
    mode: 'ro',
    name: '清扫面积',
    property: {
      unit: '㎡',
      min: 0,
      max: 9999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'clean_time',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 17,
    mode: 'ro',
    name: '清扫时间',
    property: {
      unit: 'min',
      min: 0,
      max: 9999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'fault',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_warming',
    id: 18,
    mode: 'ro',
    name: '故障告警',
    property: {
      label: [
        'edge_sweep',
        'middle_sweep',
        'left_wheel',
        'right_wheel',
        'garbage_box',
        'land_check',
        'collision',
      ],
      type: 'bitmap',
      maxlen: 7,
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'map_config',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-setting',
    id: 19,
    mode: 'ro',
    name: '地图参数配置',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 1184,
    canTrigger: false,
    code: 'water_control',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_water',
    id: 20,
    mode: 'rw',
    name: '水量控制',
    property: {
      range: ['closed', 'low', 'middle', 'high'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1088,
    canTrigger: true,
    code: 'rag_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    id: 21,
    mode: 'ro',
    name: '抹布寿命',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'rag_life_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 22,
    mode: 'rw',
    name: '抹布重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'unit_set',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 23,
    mode: 'rw',
    name: '单位设置',
    property: {
      range: ['square_meter', 'square_foot'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'work_mode',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 24,
    mode: 'rw',
    name: '工作模式',
    property: {
      range: ['both_work', 'only_sweep', 'only_mop'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 64,
    canTrigger: true,
    code: 'clean_area_total',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-tongji2',
    id: 25,
    mode: 'ro',
    name: '总清扫面积',
    property: {
      unit: '㎡',
      min: 0,
      max: 99999999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 64,
    canTrigger: true,
    code: 'clean_count_total',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-tongji2',
    id: 26,
    mode: 'ro',
    name: '总清扫次数',
    property: {
      min: 0,
      max: 99999999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 64,
    canTrigger: true,
    code: 'clean_time_total',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 27,
    mode: 'ro',
    name: '总清扫时间',
    property: {
      unit: 'min',
      min: 0,
      max: 99999999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'volume_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_voice',
    id: 28,
    mode: 'rw',
    name: '机器播报语音音量设置',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'language',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 29,
    mode: 'rw',
    name: '本地机器播报语音切换',
    property: {
      range: [
        'chinese_simplified',
        'chinese_traditional',
        'english',
        'german',
        'french',
        'russian',
        'spanish',
        'korean',
        'latin',
        'portuguese',
        'japanese',
        'italian',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
] as const;
