export enum ETimer {
  ADD_RTC_TIMER = 'ADD_RTC_TIMER',
  REMOVE_RTC_TIMER = 'REMOVE_RTC_TIMER',
  UPDATE_RTC_TIMER = 'UPDATE_RTC_TIMER',
  CLOSE_ALL_RTC_TIMER = 'CLOSE_ALL_RTC_TIMER',
  INIT_RTC_TIMER_LIST = 'INIT_RTC_TIMER_LIST',
}
