export const defaultSchema = [
  {
    attr: 1664,
    canTrigger: true,
    code: 'systolic_bp',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 1,
    mode: 'rw',
    name: '收缩压',
    property: {
      min: 1,
      max: 300,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'diastolic_bp',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 2,
    mode: 'rw',
    name: '舒张压',
    property: {
      min: 1,
      max: 300,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'pulse',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_heart',
    id: 3,
    mode: 'rw',
    name: '脉搏',
    property: {
      min: 1,
      max: 300,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'arrhythmia',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_heart',
    id: 4,
    mode: 'rw',
    name: '心率不齐',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'battery_low',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_battery',
    id: 6,
    mode: 'rw',
    name: '低电',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'user_set',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-geren',
    id: 7,
    mode: 'rw',
    name: '用户设置',
    property: {
      range: ['user1', 'user2'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'user_check',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-geren',
    id: 8,
    mode: 'rw',
    name: '用户查询',
    property: {
      range: ['all', 'user1', 'user2'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'user_mark',
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-geren',
    id: 9,
    mode: 'rw',
    name: '用户标识',
    property: {
      range: ['user1', 'user2'],
      type: 'enum',
    },
    type: 'obj',
  },
] as const;
