export const defaultSchema = [
  {
    attr: 643,
    canTrigger: true,
    code: 'switch_led',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power',
    id: 1,
    mode: 'rw',
    name: '开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'dev_info',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '{"passive":true}',
    id: 101,
    mode: 'ro',
    name: '设备信息',
    passive: true,
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'resolution',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '{"passive":true}',
    id: 102,
    mode: 'ro',
    name: '分辨率',
    passive: true,
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'playlist',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 103,
    mode: 'rw',
    name: '播放列表',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'bright',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 104,
    mode: 'rw',
    name: '亮度',
    property: {
      unit: '',
      min: 1,
      max: 15,
      scale: 1,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'del_pro',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 105,
    mode: 'wr',
    name: '删除节目',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'pic_pro',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 106,
    mode: 'rw',
    name: '图片节目',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'gif_pro',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 107,
    mode: 'rw',
    name: 'gif节目',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'text_pro',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '{"passive":true}',
    id: 108,
    mode: 'rw',
    name: '文本节目',
    passive: true,
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'time_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 109,
    mode: 'wr',
    name: '时间设置',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'gadget',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 110,
    mode: 'wr',
    name: '小工具',
    property: {
      range: ['clock', 'countdown', 'stopwatch', 'tetris', 'snake', 'tuya'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'countdown_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 111,
    mode: 'wr',
    name: '倒计时设置',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'gadget_key',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 112,
    mode: 'wr',
    name: '小工具通用功能键',
    property: {
      range: [
        'key_left',
        'key_up',
        'key_right',
        'key_down',
        'key_start',
        'key_pause',
        'key_done',
        'key_exit',
        'key_reset',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'pixel_doodle',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 113,
    mode: 'wr',
    name: '像素涂鸦',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
] as const;
